<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Maritime Logistics & Vessel Chartering in Dubai | Mare Ventus</title>
    <meta name="description" content="Dubai-based maritime logistics, vessel chartering and bulk vegetable oil transportation across Europe, Africa, the Red Sea, Persian Gulf and Caspian Sea.">
    <meta name="robots" content="index,follow,max-image-preview:large">
    <meta name="author" content="Mare Ventus Logistics FZCO">
    <meta name="yandex-verification" content="c080213a844d65ce">
    <meta name="theme-color" content="#0B3D66">
    <link rel="canonical" href="{{ url('/') }}">
    <link rel="alternate" hreflang="en" href="{{ url('/') }}">
    <meta property="og:locale" content="en_US"><meta property="og:site_name" content="Mare Ventus Logistics FZCO"><meta property="og:title" content="Mare Ventus Logistics FZCO | Maritime Logistics & Chartering"><meta property="og:description" content="Reliable maritime logistics, vessel chartering and bulk vegetable oil transportation from Dubai."><meta property="og:url" content="{{ url('/') }}"><meta property="og:image" content="{{ asset('og-image.svg') }}"><meta property="og:image:alt" content="Mare Ventus Logistics maritime cargo transportation"><meta property="og:type" content="website">
    <meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="Mare Ventus Logistics FZCO | Maritime Logistics & Chartering"><meta name="twitter:description" content="Reliable maritime logistics, vessel chartering and bulk vegetable oil transportation from Dubai."><meta name="twitter:image" content="{{ asset('og-image.svg') }}">
    <script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'LocalBusiness','additionalType'=>'https://schema.org/TransportationBusiness','name'=>'Mare Ventus Logistics FZCO','url'=>url('/'),'logo'=>asset('logo-mark.svg'),'description'=>'Maritime logistics, vessel chartering and bulk vegetable oil transportation from Dubai.','email'=>$settings['email'] ?? 'management@mareventuslog.com','telephone'=>$settings['phone'] ?? '+971 4 228 52 85','address'=>['@type'=>'PostalAddress','streetAddress'=>'Dubai Silicon Oasis, DDP (Dubai Digital Park), Building A3, Office 201A','addressLocality'=>'Dubai','addressCountry'=>'AE'],'areaServed'=>['Europe','Africa','Red Sea','Persian Gulf','Caspian Sea'],'sameAs'=>array_values(array_filter([$settings['linkedin_url'] ?? null], fn ($url) => $url && $url !== '#'))], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
    <link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="bg-white text-ink antialiased" x-data="siteApp()">
<header class="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur" :class="{'shadow-sm': scrolled}">
    <div class="site-container flex h-20 items-center justify-between">
        <a href="#top" class="flex items-center gap-3" aria-label="Mare Ventus Logistics home"><span><strong class="block text-[15px] tracking-[.2em] text-navy">MARE VENTUS</strong><small class="block text-[8px] font-semibold tracking-[.34em] text-slate-500">LOGISTICS FZCO</small></span><img src="{{ asset('logo-mark.svg') }}" alt="" class="brand-symbol h-6 w-10" aria-hidden="true"></a>
        <nav class="hidden items-center gap-9 text-sm font-semibold text-navy lg:flex" aria-label="Primary navigation">@foreach(['About','Services','Fleet','Partners','Contact'] as $item)<a class="nav-link" href="#{{ strtolower($item) }}">{{ $item }}</a>@endforeach</nav>
        <a href="#contact" class="button-primary hidden lg:inline-flex">Get in Touch <span aria-hidden="true">→</span></a>
        <button class="menu-button lg:hidden" @click="menuOpen=!menuOpen" :aria-expanded="menuOpen" aria-label="Toggle navigation"><span></span><span></span></button>
    </div>
    <nav x-cloak x-show="menuOpen" x-transition class="border-t border-slate-200 bg-white px-6 pb-6 pt-4 lg:hidden" aria-label="Mobile navigation">@foreach(['About','Services','Fleet','Partners','Contact'] as $item)<a @click="menuOpen=false" class="block border-b border-slate-100 py-3 font-semibold text-navy" href="#{{ strtolower($item) }}">{{ $item }}</a>@endforeach<a @click="menuOpen=false" class="button-primary mt-5 w-full justify-center" href="#contact">Get in Touch →</a></nav>
</header>

<main id="top">
    <section class="hero relative flex min-h-[720px] items-center overflow-hidden pt-20" aria-labelledby="hero-title">
        <img src="{{ asset('assets/images/vessel-01.webp') }}" alt="Bulk liquid cargo vessel navigating open international waters" class="absolute inset-0 h-full w-full object-cover" width="1920" height="1280" fetchpriority="high">
        <div class="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,38,65,.94)_0%,rgba(5,38,65,.78)_39%,rgba(5,38,65,.08)_70%,rgba(5,38,65,0)_100%)]"></div>
        <div class="site-container relative z-10 py-28 text-white"><div class="max-w-[880px]"><h1 id="hero-title" class="display-title">{{ $settings['hero_title'] ?? 'Reliable Ocean & River Cargo Transportation' }}</h1><div class="mt-7 max-w-2xl text-lg leading-8 text-white/84">{!! $settings['hero_text'] ?? '' !!}</div><a href="#contact" class="button-primary mt-10">Discuss Your Shipment <span aria-hidden="true">→</span></a></div></div>
        <a href="#about" class="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 text-white" aria-label="Continue to About"><span class="block h-8 w-8 rotate-45 border-b-2 border-r-2"></span></a>
    </section>

    <section id="about" class="section bg-white"><div class="site-container grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-24"><div data-reveal><p class="section-label">About us</p><h2 class="section-title mt-4">{{ $settings['about_title'] ?? 'Built for dependable movement' }}</h2><div class="section-copy mt-6 space-y-4">{!! $settings['about_text'] ?? '' !!}</div><p class="section-copy mt-4">Our mission is to provide reliable, high-quality transport services while building new routes and smarter transport schemes for our clients.</p><a class="inline-link mt-5" href="#contact">Learn more about us <span aria-hidden="true">→</span></a></div><div class="about-visual border-l-0 border-slate-200 lg:border-l lg:pl-16" data-reveal><div class="grid grid-cols-3 gap-6 border-b border-slate-200 pb-10"><div><strong class="stat">2022</strong><span class="stat-label">Founded</span></div><div><strong class="stat">5</strong><span class="stat-label">Regions</span></div><div><svg class="mb-3 h-10 w-10 text-orange" fill="none" stroke="currentColor" stroke-width="1.6" viewBox="0 0 24 24"><path d="M12 2s6 7 6 12a6 6 0 1 1-12 0c0-5 6-12 6-12Z"/></svg><span class="stat-label">Bulk Liquid Cargo</span></div></div><div class="about-map mt-8"><x-route-map compact="true" /><p class="map-tagline">Essential cargo<br>further together</p></div></div></div></section>

    <section id="services" class="section bg-mist"><div class="site-container"><div class="grid items-end gap-6 lg:grid-cols-2" data-reveal><div><p class="section-label">Our services</p><h2 class="section-title mt-4">From planning to delivery</h2></div><p class="section-copy lg:justify-self-end">Integrated logistics and chartering solutions focused on bulk vegetable oil cargo, aligning people, vessels and expertise to keep supply chains moving.</p></div><div class="mt-14 grid border-y border-slate-200 md:grid-cols-2 lg:grid-cols-4">@foreach($services as $service)<article class="service-item" data-reveal><div class="service-icon">@include('partials.icon',['name'=>$service->icon])</div><h3 class="mt-6 text-xl font-bold text-navy">{{ $service->title }}</h3><p class="mt-3 text-sm leading-6 text-slate-600">{{ $service->description }}</p></article>@endforeach</div></div></section>

    <section id="fleet" class="section bg-white"><div class="site-container"><div class="max-w-2xl" data-reveal><p class="section-label">Our fleet</p><h2 class="section-title mt-4">Vessels for dependable cargo movement</h2><p class="section-copy mt-5">Vessels operated within our chartering network support safe, efficient bulk liquid transport across key trade corridors.</p></div><div class="fleet-grid mt-12">@foreach($fleet as $index=>$image)<button class="fleet-card group text-left" @click="openLightbox('{{ str_starts_with($image->path,'assets/') ? asset($image->path) : Storage::url($image->path) }}','{{ e($image->caption) }}')" data-reveal><img src="{{ str_starts_with($image->path,'assets/') ? asset($image->path) : Storage::url($image->path) }}" alt="{{ $image->caption }}" class="h-full w-full object-cover transition duration-700 group-hover:scale-[1.03]" loading="lazy" width="800" height="560"><span class="fleet-caption">{{ $image->caption }} <b aria-hidden="true">↗</b></span></button>@endforeach</div></div></section>

    <section id="partners" class="section bg-mist"><div class="site-container grid gap-16 lg:grid-cols-[1.1fr_.9fr] lg:gap-20"><div data-reveal><p class="section-label">Our reach</p><h2 class="section-title mt-4">Connected across vital trade routes</h2><div class="mt-8"><x-route-map /></div><div class="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-navy">@foreach(['Europe','Africa','Red Sea','Persian Gulf','Caspian Sea'] as $region)<span class="flex items-center gap-2"><i class="h-2 w-2 rounded-full bg-orange"></i>{{ $region }}</span>@endforeach</div></div><div class="partner-panel border-t border-slate-200 pt-10 lg:border-l lg:border-t-0 lg:pl-16 lg:pt-0" data-reveal><p class="section-label">Our partners</p><h2 class="section-title mt-4">Trusted commercial relationships</h2><div class="partner-logos mt-10 border-y border-slate-200 py-8">@foreach($partners as $partner)<div class="partner-logo">{{ $partner->name }}</div>@if(!$loop->last)<div class="partner-divider"></div>@endif @endforeach</div><p class="section-copy mt-8">We work with leading energy and agri-commodity companies to support dependable global trade flows.</p></div></div></section>

    <section id="contact" class="section bg-white"><div class="site-container"><div class="mb-12" data-reveal><p class="section-label">Contact</p><h2 class="section-title mt-4">Plan your next shipment</h2></div><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div data-reveal><div class="contact-list"><a href="https://maps.google.com/?q={{ urlencode($settings['address'] ?? '') }}" target="_blank" rel="noopener"><span>⌖</span>{{ $settings['address'] ?? '' }}</a><a href="mailto:{{ $settings['email'] ?? '' }}"><span>✉</span>{{ $settings['email'] ?? '' }}</a><a href="tel:{{ preg_replace('/\s+/', '', $settings['phone'] ?? '') }}"><span>☎</span>{{ $settings['phone'] ?? '' }}</a></div><a class="contact-map mt-8" href="https://maps.google.com/?q={{ urlencode($settings['address'] ?? '') }}" target="_blank" rel="noopener" aria-label="Open Dubai Silicon Oasis in Google Maps"><span class="contact-map-pin">●</span><span><strong>Dubai Silicon Oasis</strong><small>DDP · Building A3 · Office 201A</small><em>Open location map ↗</em></span></a></div><form class="contact-form" @submit.prevent="submitForm($event)" novalidate data-reveal><div class="grid gap-5 sm:grid-cols-2"><label>Name*<input name="name" required autocomplete="name" placeholder="Your name"></label><label>Email*<input name="email" type="email" required autocomplete="email" placeholder="you@company.com"></label><label>Phone<input name="phone" autocomplete="tel" placeholder="+971 ..."></label><label>Company<input name="company" autocomplete="organization" placeholder="Your company"></label></div><label class="mt-5 block">Message*<textarea name="message" required minlength="10" rows="5" placeholder="How can we help you?"></textarea></label><input class="hidden" name="website" tabindex="-1" autocomplete="off"><button class="button-primary mt-6 w-full justify-center" :disabled="submitting"><span x-text="submitting ? 'Sending…' : 'Send Enquiry'"></span><span aria-hidden="true">→</span></button><p class="mt-4 text-sm" :class="formError ? 'text-red-600':'text-emerald-700'" x-text="formMessage" role="status"></p></form></div></div></section>
</main>

<footer class="bg-navy py-14 text-white"><div class="site-container grid gap-10 md:grid-cols-[.8fr_1.2fr_.5fr] md:items-start"><a href="#top" class="flex items-center gap-3"><span><strong class="block text-sm tracking-[.2em]">MARE VENTUS</strong><small class="block text-[8px] tracking-[.34em] text-white/70">LOGISTICS FZCO</small></span><img src="{{ asset('logo-mark.svg') }}" alt="" class="brand-symbol brand-symbol-light h-6 w-10" aria-hidden="true"></a><div class="text-sm leading-6 text-white/75"><strong class="block text-white">Mare Ventus Logistics FZCO</strong><p class="mt-2">{{ $settings['address'] ?? '' }}</p><a class="block hover:text-white" href="mailto:{{ $settings['email'] ?? '' }}">{{ $settings['email'] ?? '' }}</a><a class="block hover:text-white" href="tel:{{ preg_replace('/\s+/', '', $settings['phone'] ?? '') }}">{{ $settings['phone'] ?? '' }}</a></div><a href="{{ $settings['linkedin_url'] ?: '#' }}" class="font-semibold hover:text-orange">LinkedIn ↗</a></div><div class="site-container mt-12 border-t border-white/15 pt-6 text-xs text-white/55">© {{ date('Y') }} Mare Ventus Logistics FZCO. All rights reserved.</div></footer>

<div x-cloak x-show="lightbox.open" x-transition.opacity class="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/90 p-5" @keydown.escape.window="lightbox.open=false" @click.self="lightbox.open=false"><button class="absolute right-6 top-5 text-4xl text-white" @click="lightbox.open=false" aria-label="Close image">×</button><figure class="max-w-6xl"><img :src="lightbox.src" :alt="lightbox.caption" class="max-h-[82vh] w-auto"><figcaption class="mt-4 text-center text-sm text-white/80" x-text="lightbox.caption"></figcaption></figure></div>
</body></html>


